### ISSUE TITLE
Disable Active Mode Switch when no Thermostat Defined

### ISSUE THREAD

**Issue by samphonic** [muart-group/esphome#35]
Only define `active_mode_switch` if `uart_thermostat` is defined in YAML (it serves no purpose otherwise).

**Comment by nagyrobi** [comment]
If `uart_thermostat` is defined in YAML, then `active_mode_switch` is required. Otherwise `active_mode_switch` remains optional.

**Comment by KazWolfe** [comment]
Consider also making this purely a compile-time flag; I don't see much value in having it be toggleable at runtime, and features like #30 *will* cause significant problems if users can swap between active and passive modes.

**Comment by KazWolfe** [comment]
Resolved in #42.
